In [7]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
x = 12
print(a+x)

[[13 14 15]
 [16 17 18]]


BROADCASTING A SCALER AT 1D ARRAY

In [9]:
import numpy as np
arr = np.array([1,2,3,4])
res = arr +1
res

array([2, 3, 4, 5])

In [20]:
import numpy as np
a = np.array([1,2,3,4])
b = np.array([[2,3,4,5],[6,7,8,9]])
res = a+b
res

array([[ 3,  5,  7,  9],
       [ 7,  9, 11, 13]])